name: Publish

on:
  push:
    branches: ['main']

jobs:
  releases-matrix:
    name: release binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }} 
        project_path: "./nrt-cli"
        binary_name: "nrt"
        release_tag: "latest"
        overwrite: TRUE
        extra_files: LICENSE README.md
